export const REEL_REVEAL_SCRATCH_THRESHOLD = 0.42;
export const REEL_REVEAL_REEL_SPIN_INTERVAL_MS = 72;
export const REEL_REVEAL_REEL_STOP_DELAYS_MS = [1050, 1550, 2125] as const;
export const REEL_REVEAL_COUNT_UP_MS = 1650;

